# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Polyverse Demo"
email: support@polyverse.io
description: > # this means to ignore newlines until "baseurl:"
  Polyverse Demos
  
baseurl: # the subpath of your site, e.g. /blog
url: "http://demo.polyverse.io" # the base hostname & protocol for your site

#sidebar
default-image: polyverse_logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Polyverse
copyright:
   name: Polyverse Corporation
   link: 'https://polyverse.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-65028710-9


#social
facebook: https://www.facebook.com/polyverse.io
twitter: https://twitter.com/polyverse_io
github: https://github.com/polyverse/demo-polyverse.github.io
twitter_username: polyverse_io
youtube: https://www.youtube.com/channel/UCStfUTkXcU-zLF0qiAN0tWw

#facebook like box
fb-app-id: 181771615496034
fb-page-url: https://www.facebook.com/polyverse.io/
fb-page-title: Polyverse

# Sass style
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate

# Polyverse Demo
pwkurl: https://demo.polyverse.io

